FactoryGirl.define do
  factory :campaign_schedule_placement do
    uid ""
code "MyString"
code_external "MyString"
media_category nil
campaign nil
campaign_schedule nil
client_product nil
client_product_sub nil
client_contact nil
creative_agency nil
creative_agency_contact nil
media_agency_client nil
media_agency_client_contact nil
natural_client nil
natural_client_product nil
natural_client_contact nil
media_space nil
business_unit nil
media_space_section nil
media_space_part nil
media_category_size nil
media_category_format nil
media_frequency_cap_type nil
supplier nil
supplier_contact nil
owner_user nil
manager_user nil
currency nil
exchange_rate "9.99"
rate_type nil
rate_card_line nil
cost_type nil
quantity_per_unit_rate "9.99"
quantity "9.99"
rate_card_unit_cost_gross "9.99"
rate_card_unit_cost_gross_home "9.99"
rate_card_unit_cost_nett "9.99"
rate_card_unit_cost_nett_home "9.99"
rate_card_cost_gross "9.99"
rate_card_cost_gross_home "9.99"
rate_card_cost_nett "9.99"
rate_card_cost_nett_home "9.99"
commission_supplier_percentage "9.99"
commission_supplier_amount "9.99"
commission_supplier_home_amount "9.99"
commission_agency_percentage "9.99"
commission_agency_amount "9.99"
commission_agency_home_amount "9.99"
effective_discount_percentage "9.99"
effective_discount_amount "9.99"
effective_discount_home_amount "9.99"
effective_discount_to_client_percentage "9.99"
effective_discount_to_client_amount "9.99"
effective_discount_to_client_home_amount "9.99"
cost_gross "9.99"
cost_gross_home "9.99"
cost_nett "9.99"
cost_nett_home "9.99"
minimum_intermediary_margin_percentage "9.99"
minimum_intermediary_margin_amount "9.99"
minimum_intermediary_margin_home_amount "9.99"
effective_intermediary_margin_percentage "9.99"
effective_intermediary_margin_amount "9.99"
effective_intermediary_margin_home_amount "9.99"
actual_cost_nett "9.99"
actual_cost_nett_home "9.99"
supplier_invoiced_cost_to_date_amount "9.99"
supplier_invoiced_cost_to_date_home_amount "9.99"
supplier_invoiced_cost_commission_to_date_amount "9.99"
supplier_invoiced_cost_commission_to_date_home_amount "9.99"
supplier_invoiced_cost_nett_to_date_amount "9.99"
supplier_invoiced_cost_nett_to_date_home_amount "9.99"
supplier_invoiced_intermediary_margin_to_date_amount "9.99"
supplier_invoiced_intermediary_margin_to_date_home_amount "9.99"
supplier_invoiced_actual_cost_nett_to_date_amount "9.99"
supplier_invoiced_actual_cost_nett_to_date_home_amount "9.99"
fees "9.99"
fees_home "9.99"
fees_to_date "9.99"
fees_to_date_home "9.99"
production_cost_amount "9.99"
production_cost_home_amount "9.99"
ordered_production_cost_amount_to_date "9.99"
ordered_production_cost_amount_to_date_home "9.99"
supplier_invoiced_production_cost_to_date_amount "9.99"
supplier_invoiced_production_cost_to_date_home_amount "9.99"
effective_production_cost_margin_percentage "9.99"
production_cost_margin_amount "9.99"
production_cost_margin_home_amount "9.99"
production_cost_margin_to_date_amount "9.99"
production_cost_margin_to_date_home_amount "9.99"
production_client_billable_amount "9.99"
production_client_billable_home_amount "9.99"
production_client_invoiced_to_date_amount "9.99"
production_client_invoiced_to_date_home_amount "9.99"
client_billable_gross_amount "9.99"
client_billable_gross_home_amount "9.99"
client_billable_nett_amount "9.99"
client_billable_nett_home_amount "9.99"
client_invoiced_to_date_cost_gross_home_amount "9.99"
client_invoiced_to_date_cost_commission_home_amount "9.99"
client_invoiced_to_date_cost_nett_home_amount "9.99"
client_invoiced_to_date_gross_amount "9.99"
client_invoiced_to_date_gross_home_amount "9.99"
client_invoiced_to_date_fees_amount "9.99"
client_invoiced_to_date_fees_home_amount "9.99"
client_invoiced_to_date_production_costs_with_margin_amount "9.99"
client_invoiced_to_date_production_costs_with_margin_home_amount "9.99"
client_invoiced_to_date_nett_amount "9.99"
client_invoiced_to_date_nett_home_amount "9.99"
cost_billing_gross_home_difference_amount "9.99"
cost_billing_commission_home_difference_amount "9.99"
cost_billing_nett_home_difference_amount "9.99"
supplier_invoiced_provision_gross_home_amount "MyString"
  end

end
