FactoryGirl.define do
  factory :client_financial_document do
    uid ""
code "MyString"
code_external 1
company nil
company_division nil
client nil
client_product nil
contact nil
campaign nil
campaign_schedule nil
owner_user nil
currency nil
creation_source nil
status nil
communication_status nil
actual_date "2014-12-25"
posting_date "2014-12-25"
cost_gross_amount "9.99"
cost_commission_amount "9.99"
cost_nett_amount "9.99"
cost_gross_home_amount "9.99"
cost_commission_home_amount "9.99"
cost_nett_home_amount "9.99"
production_costs_amount "9.99"
production_costs_home_amount "9.99"
production_costs_margin_amount "9.99"
production_costs_margin_home_amount "9.99"
gross_amount "9.99"
commission_amount "9.99"
fees_amount "9.99"
production_costs_with_margin_amount "9.99"
nett_amount "9.99"
nett_inc_tax_amount "9.99"
gross_home_amount "9.99"
commission_home_amount "9.99"
fees_home_amount "9.99"
production_costs_with_margin_home_amount "9.99"
nett_home_amount "9.99"
nett_inc_tax_home_amount "9.99"
tax_type nil
tax_gross_amount "9.99"
tax_nett_amount "9.99"
exchange_rate "9.99"
notes "MyString"
status_reason "MyString"
grid_layout_x_m_l "MyString"
eis_sync_date "2014-12-25 16:41:26"
rate_card_unit_cost_gross "9.99"
rate_card_unit_cost_gross_home "9.99"
rate_card_unit_cost_nett "9.99"
rate_card_unit_cost_nett_home "9.99"
rate_card_cost_gross "9.99"
rate_card_cost_gross_home "9.99"
rate_card_cost_nett "9.99"
rate_card_cost_nett_home "9.99"
commission_agency_amount "9.99"
commission_agency_home_amount "9.99"
effective_discount_amount "9.99"
effective_discount_home_amount "9.99"
effective_discount_to_client_amount "9.99"
effective_discount_to_client_home_amount "9.99"
client_purchase_order nil
cost_minimum_intermediary_margin_percentage "9.99"
cost_minimum_intermediary_margin_amount "9.99"
cost_minimum_intermediary_margin_home_amount "9.99"
actual_cost_nett "9.99"
actual_cost_nett_home "9.99"
company_cost_centre nil
  end

end
