FactoryGirl.define do
  factory :company_division do
    uid ""
code "MyString"
name "MyString"
legal_name "MyString"
company nil
default_media_category nil
item_no_suffix "MyString"
is_active false
is_test_division false
contact nil
default_media_region nil
phone_number "MyString"
phone_number2 "MyString"
fax_number "MyString"
e_mail "MyString"
website "MyString"
postal_address "MyString"
physical_address "MyString"
company_registration_no "MyString"
tax_registration_no "MyString"
default_tax_type nil
default_agency_commission_type nil
default_agency_commission_percentage "9.99"
bank_details "MyString"
payment_terms_default "MyString"
notes "MyString"
report_footer "MyString"
g_l_acc_no_sales "MyString"
g_l_acc_no_purchases "MyString"
g_l_acc_no_creditors_control "MyString"
g_l_acc_no_receivable_credit_control "MyString"
g_l_acc_no_provision_for_costs "MyString"
g_l_acc_no_deferred_commission "MyString"
g_l_acc_no_output_tax_type nil
g_l_acc_no_output_adjustment_tax_type nil
g_l_acc_no_inter_comp "MyString"
g_l_acc_no_local_inter_comp "MyString"
g_l_acc_no_receivable_credit_control3 "MyString"
g_l_acc_no_cost_of_sales "MyString"
g_l_acc_no_stock "MyString"
account_default_work_type_alt_ref_no "MyString"
account_default_media_fees_alt_ref_no "MyString"
logo_file_name "MyString"
logo_alignment "MyString"
logo_resizing "MyString"
m_i_show_only_revised_placements false
m_i_create_by_media_product false
is_m_p_with_order_no_cancel_allowed false
m_p_with_order_no_cancel_allowed_exception "MyString"
is_placement_book_only_allowed_if_product_region_specified false
is_placement_exchange_rate_updated_b4_billing false
is_placement_size_and_columns_controlled false
is_placement_order_no_locked false
is_campaign_order_no_copied_to_schedule false
is_order_no_required_for_billing_default false
is_client_credit_profile_system_enabled false
default_currency nil
financial_year_end 1
is_forex_system_enabled false
is_client_fees_system_enabled false
is_rate_cards_system_enabled false
is_discount_cards_system_enabled false
is_global_agency_commission_enforced false
is_supplier_financial_document_finalize_required false
is_chase_list_required_to_create_production_purchase_order false
c_eis_sync_date "2014-12-25 16:41:44"
allow_overpay_of_placement false
is_campaign_schedule_end_date_end_of_month false
server_export_path "MyString"
client_financial_document_footer "MyString"
client_cost_estimate_footer "MyString"
legal_notice "MyString"
client_purchase_order_footer "MyString"
production_supplier_purchase_order_footer "MyString"
supplier_order_request_footer "MyString"
supplier_order_footer "MyString"
is_quantity_for_display_auto_maintained false
chase_list_footer "MyString"
client_contract_footer "MyString"
postal_address1 "MyString"
postal_address2 "MyString"
physical_address1 "MyString"
physical_address2 "MyString"
phone_number3 "MyString"
phone_number4 "MyString"
fax_number1 "MyString"
fax_number2 "MyString"
e_mail1 "MyString"
e_mail2 "MyString"
is_campaign_schedule_placement_grouped_for_chase_list_wizard false
  end

end
