json.array!(@supplier_financial_document_system_app_integration_export_batches) do |supplier_financial_document_system_app_integration_export_batch|
  json.extract! supplier_financial_document_system_app_integration_export_batch, :id, :uid, :code, :supplier_financial_document_id, :is_success, :result_message
  json.url supplier_financial_document_system_app_integration_export_batch_url(supplier_financial_document_system_app_integration_export_batch, format: :json)
end
